Level = {
	board : {
		0: {type: 'Tower', color:'Blue', x: 0, y: 0},
		1: {type: 'Tower', color:'Blue', x: 7, y: 0},
		2: {type: 'Knight', color:'Blue', x: 6, y: 0},
		3: {type: 'Knight', color:'Blue', x: 1, y: 0},
		4: {type: 'Bishop', color:'Blue', x: 5, y: 0},
		5: {type: 'Bishop', color:'Blue', x: 2, y: 0},
		6: {type: 'King', color:'Blue', x: 4, y: 0},
		7: {type: 'Queen', color:'Blue', x: 3, y: 0},
		8: {type: 'Pawn', color:'Blue', x: 0, y: 1},
		9: {type: 'Pawn', color:'Blue', x: 1, y: 1},
		10: {type: 'Pawn', color:'Blue', x: 2, y: 1},
		11: {type: 'Pawn', color:'Blue', x: 3, y: 1},
		12: {type: 'Pawn', color:'Blue', x: 4, y: 1},
		13: {type: 'Pawn', color:'Blue', x: 5, y: 1},
		14: {type: 'Pawn', color:'Blue', x: 6, y: 1},
		15: {type: 'Pawn', color:'Blue', x: 7, y: 1},
		
		16: {type: 'Tower', color:'Yellow', x: 0, y: 7},
		17: {type: 'Tower', color:'Yellow', x: 7, y: 7},
		18: {type: 'Knight', color:'Yellow', x: 6, y: 7},
		19: {type: 'Knight', color:'Yellow', x: 1, y: 7},
		20: {type: 'Bishop', color:'Yellow', x: 5, y: 7},
		21: {type: 'Bishop', color:'Yellow', x: 2, y: 7},
		22: {type: 'King', color:'Yellow', x: 4, y: 7},
		23: {type: 'Queen', color:'Yellow', x: 3, y: 7},
		24: {type: 'Pawn', color:'Yellow', x: 0, y: 6},
		25: {type: 'Pawn', color:'Yellow', x: 1, y: 6},
		26: {type: 'Pawn', color:'Yellow', x: 2, y: 6},
		27: {type: 'Pawn', color:'Yellow', x: 3, y: 6},
		28: {type: 'Pawn', color:'Yellow', x: 4, y: 6},
		29: {type: 'Pawn', color:'Yellow', x: 5, y: 6},
		30: {type: 'Pawn', color:'Yellow', x: 6, y: 6},
		31: {type: 'Pawn', color:'Yellow', x: 7, y: 6},		
	},
	name : 'Level Debug',
	description : 'Aufgabe: Setze deinen Gegner Matt !! (Noch nicht implementiert ist: Rochade, Bauernumwandlung, En-Passon, Patt)',
	win: 3
}