Level = {
	board : {
		0: {type: 'Chip', color:'Yellow', x: 1, y: 2},
		1: {type: 'Chip', color:'Yellow', x: 1, y: 3},
		2: {type: 'Chip', color:'Yellow', x: 1, y: 4},
		3: {type: 'Chip', color:'Yellow', x: 1, y: 5},
		4: {type: 'Chip', color:'Red', x: 2, y: 2},
		5: {type: 'Chip', color:'Red', x: 2, y: 3},
		6: {type: 'Chip', color:'Red', x: 2, y: 4},
		7: {type: 'Chip', color:'Red', x: 2, y: 5},
		8: {type: 'Chip', color:'Red', x: 3, y: 2},
		9: {type: 'Chip', color:'Red', x: 3, y: 3},
		10: {type: 'Chip', color:'Red', x: 3, y: 4},
		11: {type: 'Chip', color:'Red', x: 3, y: 5},
		12: {type: 'Chip', color:'Red', x: 4, y: 2},
		13: {type: 'Chip', color:'Red', x: 4, y: 3},
		14: {type: 'Chip', color:'Red', x: 4, y: 4},
		15: {type: 'Chip', color:'Red', x: 4, y: 5},
		16: {type: 'Chip', color:'Red', x: 5, y: 2},
		17: {type: 'Chip', color:'Red', x: 5, y: 3},
		18: {type: 'Chip', color:'Red', x: 5, y: 4},
		19: {type: 'Chip', color:'Red', x: 5, y: 5},
		20: {type: 'Chip', color:'Blue', x: 6, y: 2},
		21: {type: 'Chip', color:'Blue', x: 6, y: 3},
		22: {type: 'Chip', color:'Blue', x: 6, y: 4},
		23: {type: 'Chip', color:'Blue', x: 6, y: 5},
		24: {type: 'Tower', color:'Yellow', x: 0, y: 7},
		25: {type: 'Tower', color:'Blue', x: 7, y: 0},
	},
	name: '2 Spieler - Turm - Level 1',
	description : 'Jedem seine Reihe von Chips!',
	win: 0
}