Level = {
	board : {
		0: {type: 'Chip', color:'Blue', x: 1, y: 1},
		1: {type: 'Chip', color:'Blue', x: 1, y: 3},
		2: {type: 'Chip', color:'Blue', x: 2, y: 5},
		3: {type: 'Chip', color:'Blue', x: 5, y: 2},
		4: {type: 'Chip', color:'Blue', x: 6, y: 4},
		5: {type: 'Chip', color:'Blue', x: 6, y: 6},
		6: {type: 'Chip', color:'Yellow', x: 1, y: 2},
		7: {type: 'Chip', color:'Yellow', x: 1, y: 5},
		8: {type: 'Chip', color:'Yellow', x: 3, y: 5},
		9: {type: 'Chip', color:'Yellow', x: 4, y: 2},
		10: {type: 'Chip', color:'Yellow', x: 6, y: 2},
		11: {type: 'Chip', color:'Yellow', x: 6, y: 5},
		12: {type: 'Chip', color:'Red', x: 2, y: 1},
		13: {type: 'Chip', color:'Red', x: 2, y: 2},
		14: {type: 'Chip', color:'Red', x: 2, y: 3},
		15: {type: 'Chip', color:'Red', x: 1, y: 6},
		16: {type: 'Chip', color:'Red', x: 2, y: 6},
		17: {type: 'Chip', color:'Red', x: 3, y: 6},
		18: {type: 'Chip', color:'Red', x: 4, y: 1},
		19: {type: 'Chip', color:'Red', x: 5, y: 1},
		20: {type: 'Chip', color:'Red', x: 6, y: 1},
		21: {type: 'Chip', color:'Red', x: 5, y: 4},
		22: {type: 'Chip', color:'Red', x: 5, y: 5},
		23: {type: 'Chip', color:'Red', x: 5, y: 6},
		24: {type: 'Queen', color:'Blue', x: 3, y: 0},
		25: {type: 'Queen', color:'Yellow', x: 3, y: 7},
	},
	name: '2 Spieler - Dame - Level 9',
	description : 'Unübersichtlich mit einigen Hindernissen.',
	win: 0
}